# Generated by Django 4.2 on 2024-06-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_specification_size_gallery_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery", options={"verbose_name_plural": "Product Images"},
        ),
    ]
